### ISSUE TITLE
Add About page and footer

### ISSUE THREAD

**Issue by sfkeller** [mapbox/osm-comments-frontend#43]
Add "About..." page and a footer inlcuding weblinks like this:
"© OpenStreetMap contributors | Improve this map"

**Comment by batpad** [comment]
@sfkeller thank you so much for the issues.

Have added an About modal with a brief description that includes a link to the OpenStreetMap copyright notice. Do you feel a footer is still required? 

Not sure "Improve this map" really makes sense since we don't really have a slippy map anywhere on the page, but will think about this.

**Comment by batpad** [comment]
Added About link to a footer. Closing. @sfkeller please feel free to re-open if you think this could be improved.
