### ISSUE TITLE
mysterious mapbox users filter

### ISSUE THREAD

**Issue by harry-wood** [mapbox/osm-comments-frontend#56]
I was just having a play, trying out viewing notes in London using this tool with this URL https://www.mapbox.com/osm-comments/#/notes/?q=bbox%3A0.3021%2C51.7253%2C-0.5576%2C51.2550    but is seems as though there's an additional filter going on, maybe it's filtering just mapbox data team users? Any way of using the tool for browsing notes from all users?

**Comment by batpad** [comment]
Hey @harry-wood - yes, since we are primarily using this as an internal tool, the default is to search through all users of our team.

You can easily over-ride this, though by searching for `users:*` - example search: https://www.mapbox.com/osm-comments/#/notes/?q=users%3A%2A

Will add this to documentation. Thanks for pointing it out.

**Comment by batpad** [comment]
And multiple filters can be just space-separated, so for the bounding box query, you'd have something like https://www.mapbox.com/osm-comments/#/notes/?q=bbox:0.3021,51.7253,-0.5576,51.2550%20users:*

Thanks again for trying it out and would appreciate any more feedback.

**Comment by batpad** [comment]
Also, just to add, the users are defined in https://github.com/mapbox/osm-comments/blob/mb-pages/app/config.js#L6 . Hope that clears the mystery :) - am creating a ticket to make the documentation around this better.

**Comment by SomeoneElseOSM** [comment]
Thanks - never thought of using "space" as a separator.
